llama-server \
  -m /Users/jethroestrada/.cache/llama.cpp/embed_models/nomic-embed-text-v2-moe.Q4_K_M.gguf \
  --embedding \
  --pooling cls \
  --host 0.0.0.0 \
  --port 8081 -c 8192 -ub 8192 -b 8192 \
  --n-gpu-layers -1 \
  --threads 10 \
  --threads-batch 10 \
  --mlock \
  --no-mmap \
  --flash-attn on \
  --cache-type-k f16 \
  --cache-type-v f16 \
  --cont-batching \
  --parallel 4 \
  --threads-http 4 \
