llama-server \
  --model /Users/jethroestrada/.cache/llama.cpp/llm_models/mistralai_Ministral-3-3B-Instruct-2512-Q4_K_M.gguf \
  --mmproj /Users/jethroestrada/.cache/llama.cpp/llm_models/mmproj-mistralai_Ministral-3-3B-Instruct-2512-f16.gguf \
  --ctx-size 8192 \
  --n-gpu-layers all \
  --flash-attn on \
  --threads 4 \
  --threads-batch 4 \
  --batch-size 1024 \
  --ubatch-size 512 \
  --mlock \
  --host 0.0.0.0 \
  --port 8080 \
  --no-mmap \
  --cont-batching \
  --cache-type-k q8_0 \
  --cache-type-v q8_0 \
  --jinja
